### ISSUE TITLE
Load in 8 GB RAM CPU

### ISSUE THREAD

**Issue by owais3901** [kuutsav/llm-toys#1]
Hello, Hope you doing well!! . Is it possible to run the Red Pajama 3B paraphrase model on 8 GB Ram without GPU. I am getting (Killed) in my terminal after loading the model.

**Comment by kuutsav** [comment]
The 4bit quanitzed loras don't support cpu right now afaik. Hasn't worked for me at least. I'm planning to do full-finetune of even smaller models in some time, you can try those in 8gb.

**Comment by owais3901** [comment]
Thnaks
